"""Add AI fields

Revision ID: 9b2b563ebba4
Revises: 9db222bb952a
Create Date: 2026-07-28 00:11:18.264551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b2b563ebba4'
down_revision = '9db222bb952a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_reply', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('ai_reply')
        batch_op.drop_column('ai_summary')

    # ### end Alembic commands ###
